### ISSUE TITLE
メイン：基準点を一番上に表示するモード

### ISSUE THREAD

**Issue by HoNKoT** [globaltimer/Android-App#24]
リストアップ表示時に基準点を一番上に表示する

EDITモード中はどうする？
EDITモードから戻ってきたときに反映するといいかも？

**Comment by HoNKoT** [comment]
@Saayaman 
これ結局なしでオッケー？

**Comment by Saayaman** [comment]
アニメーションを入れない限りはなし！
なので、今回は見送り
