### ISSUE TITLE
アプリアイコン

### ISSUE THREAD

**Issue by HoNKoT** [globaltimer/Android-App#50]
公開までに必要なもの
・アイコン（512 x 512）
・バナー（1024 x 500）

<img width="595" alt="screen shot 2017-03-06 at 5 48 24 pm" src="https://cloud.githubusercontent.com/assets/2055607/23638234/2a274b60-0295-11e7-9ad9-7963ed00fa16.png">

アプリの説明とかもひつようだけど、あとまわし

**Comment by Saayaman** [comment]
第一弾アイデア
Ios向け
![app_icon_template](https://cloud.githubusercontent.com/assets/23070666/23720797/9fe0d50a-03f4-11e7-90c8-bfec4aad4cb1.jpg)

**Comment by Saayaman** [comment]
Android
![screen shot 2017-03-08 at 2 45 31 pm](https://cloud.githubusercontent.com/assets/23070666/23727710/f3802b0c-040d-11e7-82dd-f5e295522d27.png)
![screen shot 2017-03-08 at 2 44 51 pm](https://cloud.githubusercontent.com/assets/23070666/23727711/f380a1ae-040d-11e7-9f67-b7657c4fdbdc.png)

**Comment by HoNKoT** [comment]
異論ございません！！

**Comment by Saayaman** [comment]
IOS向け
![icon_2 0 0](https://cloud.githubusercontent.com/assets/23070666/23728081/c83e06a6-040f-11e7-8833-3af5fb879138.png)
Android向け
![android_icon](https://cloud.githubusercontent.com/assets/23070666/23728228/9ef84634-0410-11e7-81ab-4df6c0fd330a.png)

**Comment by Saayaman** [comment]
終わった
