### ISSUE TITLE
比較画面：アイコンがズレてる

### ISSUE THREAD

**Issue by HoNKoT** [globaltimer/Android-App#61]
![device-2017-03-07-172850](https://cloud.githubusercontent.com/assets/2055607/23685975/c80da4ac-035b-11e7-86a1-a92a7f60d1de.png)

**Comment by HoNKoT** [comment]
意図的だったらOK

**Comment by Saayaman** [comment]
これは白のマージンと揃っているからoK

**Comment by HoNKoT** [comment]
open
