### ISSUE TITLE
特定操作下でのクラッシュ

### ISSUE THREAD

**Issue by creaaa** [globaltimer/Android-App#75]
すみません、特定操作下でクラッシュすることを発見しましたので報告いたします。
このバグは既知でしょうか？

1. Time Nowで表示される都市が2つ以上のとき、ピンされた都市をスワイプなどで削除する
2. Set Time画面にいくと、ピンされた都市がないため、空欄になっている。
この状態で 日付ピッカーを表示する / 時間±30minボタンを押す / 各都市セルをタッチする...
などのアクションを発生させるとクラッシュする

環境はAndroid 4.4(KitKat)です。
よろしくお願いいたします><

**Comment by HoNKoT** [comment]
既知です！
https://github.com/globaltimer/Android-App/issues/59
で解決予定

**Comment by creaaa** [comment]
既知でしたか！安心しました。
何卒よろしくお願いいたします。
